name: CO₂ Forecast MLOps Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install --dev --deploy
    
    - name: Run unit tests
      run: |
        pipenv run pytest tests/test_data_processing.py -v
    
    - name: Run linting (if configured)
      run: |
        echo "Linting would go here"
  
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t co2-forecast-api:${{ github.sha }} .
        docker tag co2-forecast-api:${{ github.sha }} co2-forecast-api:latest
    
    - name: Save Docker image
      run: |
        docker save co2-forecast-api:latest > co2-forecast-api.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: co2-forecast-api.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image
    
    - name: Deploy to staging
      run: |
        echo "Deployment to staging would go here"
        echo "Could use docker-compose, k8s, cloud services, etc."
